### ISSUE TITLE
Rename functions package

### ISSUE THREAD

**Issue by soypat** [faculerena/bugtracker#1]
Hey, Awesome project!

I have one nitpick: could we rename 'cmd/functions' to 'cmd/tracker'? This would mean that namespace would be more natural, i.e. the tracker.Bug type.

If this sounds good to you maybe consider renaming Tracker type to something else to avoid the tracker.Tracker stutter. Ideas: Store, DB, Table, Bugs (plural of Bugs since it is just a list of bugs!)

**Comment by faculerena** [comment]
Yes, the tracker.Tracker stutter looks bad.

The cmd/functions > cmd/tracker change is logical, didn't think about that, I almost called that "methods"

Thanks, I will apply this changes!

**Comment by faculerena** [comment]
https://github.com/faculerena/bugtracker/commit/886b4da8721c8e77fb3f638fbac5a3ec8904abc2

**Comment by faculerena** [comment]
I think that's better, thanks!
